### ISSUE TITLE
"is Retweet?" always true problem

### ISSUE THREAD

**Issue by Tengchieh** [rahulha/OrgneatUI#3]
I think "is Retweet?" means whether the current tweet is a retweet or not, right? Then this attribute might exist a bug. I look into your code. Is it probably your collector only search for "retweeted" existing in the tweet object? Can you search existing of "retweeted_status" instead?
Sorry I am not so familiar with C# that I could not fix it by myself. If someone could do it for me, it would be greatly appreciated.

**Comment by rahulha** [comment]
isRetweet appparently is coming from Twitter as a flag. I may have code to check retweet text. I will make that change soon. Thanks for letting me know.
