### ISSUE TITLE
Not working all of a sudden

### ISSUE THREAD

**Issue by joanacarlos5** [rahulha/OrgneatUI#5]
The app was working perfectly, but now it does not work for any type of search that I try. I am attaching the error that I get. I checked and there are indeed Twitter responses for those periods. I do not know what to do. Can you please tell me how can I fix it?

To add some context: I am trying to scrape english tweets from 9th to 11th of April 2017 with the @united mention for my thesis. 
 
![error](https://user-images.githubusercontent.com/48844899/54857502-edb5d900-4cff-11e9-9734-dba070fd5560.PNG)

**Comment by rahulha** [comment]
Hi, as per our communication, please confirm and close this issue.
