### ISSUE TITLE
Not respecting language choice

### ISSUE THREAD

**Issue by ppival** [rahulha/OrgneatUI#6]
Really neat, thanks! It doesn't appear to be respecting my language choice of English. The syntax of the test query returns all languages: 
https://twitter.com/search?f=tweets&q=whatever%20since:2018-1-1%20until:2018-12-31&lang=en&src=typd

If I tweak that on the twitter advanced search page, the following URL **does** appear to work:

https://twitter.com/search?f=tweets&q=whatever%20since%3A2018-1-1%20until%3A2018-12-31&l=en&src=typd

suggest maybe the syntax needs to change from **lang=en** to **l=en** ?

**Comment by rahulha** [comment]
Hi,
I am surprised no one ever came across this bug. Thank you for reporting this. It was just matter of changing lang to l in query string which I missed. There is another lang parameter for the result's language itself I think. Never mind I made the update and uploaded latest code with executable :-)

Please test and close this issue.

**Comment by rahulha** [comment]
code updated

**Comment by ppival** [comment]
Confirmed working, thanks!
